# Generated by Django 5.1.4 on 2025-03-05 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_category_categorydescription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='test_field',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'product')},
        ),
    ]
