# Generated by Django 5.1.4 on 2025-03-20 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_order_shipping_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='orderPrice',
        ),
    ]
