# Generated by Django 5.1.4 on 2025-03-20 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_remove_orderitem_orderprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='razorpay_order_id',
        ),
    ]
