# Generated by Django 5.1.4 on 2025-03-20 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_order_shipping_address_order_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
