# Generated by Django 5.1.4 on 2025-03-20 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_alter_order_shipping_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
