# Generated by Django 5.1.4 on 2025-03-20 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_remove_order_razorpay_order_id_order_payment_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='price',
        ),
    ]
