# Generated by Django 5.1.4 on 2025-03-27 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
