# Generated by Django 5.1.4 on 2025-04-03 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_delete_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
